### ISSUE TITLE
Horizontal scrolling through homepage carousels triggers scroll-to-top

### ISSUE THREAD

**Issue by xingyzt** [AHSAppDevTeam/Arcadia-High-Mobile-Android#3]
Steps to reproduce:

1. Open app
2. Navigate to home page
3. Scroll down a bit
4. Lightly scroll a carousel that isn't the featured carousel (not enough length to scroll right a whole card.

Expected: Carousel snaps to one card or another

Actual: Along with the expected result, the app also suddenly scrolls to the top of the home page.

AHS Mobile v.3.1.1
Android v.5.1.1
LG G Stylo

**Comment by jeffreyAaron** [comment]
This issue no longer occurs on the new app.
